# Generated by Django 3.0.8 on 2020-08-02 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(blank=True)),
                ('f_name', models.CharField(blank=True, max_length=16)),
                ('birthday', models.IntegerField(blank=True)),
                ('n_id', models.IntegerField(blank=True)),
                ('file_number', models.IntegerField(blank=True)),
                ('degree', models.CharField(blank=True, max_length=64)),
                ('field', models.CharField(blank=True, max_length=64)),
                ('university', models.CharField(blank=True, max_length=64)),
                ('rank', models.CharField(blank=True, max_length=32)),
                ('job', models.CharField(blank=True, max_length=64)),
                ('t_year', models.IntegerField(blank=True)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('mobile', models.IntegerField(blank=True)),
                ('phone', models.IntegerField(blank=True)),
                ('account', models.IntegerField(blank=True)),
                ('bank', models.CharField(blank=True, max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
