# Generated by Django 3.0.8 on 2020-10-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200817_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_intership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intership_pay',
            field=models.IntegerField(default=0),
        ),
    ]
