# Generated by Django 3.0.8 on 2020-10-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201013_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='is_intership',
            field=models.CharField(choices=[('نظری - عملی', 'نظری - عملی'), ('کارورزی', 'کارورزی')], default='نظری - عملی', max_length=16),
        ),
    ]
