# Generated by Django 3.0.8 on 2020-08-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200807_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('آقا', 'آقا'), ('خانم', 'خانم')], default='آقا', max_length=8),
        ),
    ]
