# Generated by Django 3.0.8 on 2020-10-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_term'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Term',
        ),
    ]
