# Generated by Django 3.0.8 on 2020-10-16 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('std_id', models.IntegerField(default=0)),
                ('n_id', models.IntegerField(default=0)),
                ('field', models.CharField(max_length=64)),
                ('degree', models.CharField(choices=[('کاردانی', 'کاردانی'), ('کارشناسی ناپیوسته', 'کارشناسی ناپیوسته')], default='کارشناسی', max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('score', models.IntegerField(default=0)),
                ('score_letters', models.CharField(max_length=32)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
