# Generated by Django 3.0.8 on 2020-10-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0003_auto_20201016_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='question1_desc',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='question1_value',
            field=models.CharField(choices=[('-', '-'), ('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('غیر قابل قبول', 'غیر قابل قبول')], default='-', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='question2_desc',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='question2_value',
            field=models.CharField(choices=[('-', '-'), ('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('غیر قابل قبول', 'غیر قابل قبول')], default='-', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='question3_desc',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='question3_value',
            field=models.CharField(choices=[('-', '-'), ('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('غیر قابل قبول', 'غیر قابل قبول')], default='-', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='question4_desc',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='question4_value',
            field=models.CharField(choices=[('-', '-'), ('عالی', 'عالی'), ('خوب', 'خوب'), ('متوسط', 'متوسط'), ('غیر قابل قبول', 'غیر قابل قبول')], default='-', max_length=16),
        ),
        migrations.DeleteModel(
            name='ProjectQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
