# Generated by Django 3.0.8 on 2020-10-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0004_auto_20201017_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='question1_desc',
            new_name='desc_question1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='question2_desc',
            new_name='desc_question2',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='question3_desc',
            new_name='desc_question3',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='question4_desc',
            new_name='desc_question4',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='question1_value',
            new_name='value_question1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='question2_value',
            new_name='value_question2',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='question3_value',
            new_name='value_question3',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='question4_value',
            new_name='value_question4',
        ),
    ]
